theme: minima
title: K's Web Growth
author: KM
email: kem10180@gmail.com
description: My personal growth with JavaScript and GitHub

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
